// Transcript extraction content script — injected into the active tab to detect
// and extract video transcripts from supported platforms.
//
// Injected via chrome.scripting.executeScript from the service worker.
// Sends results back via chrome.runtime.sendMessage.
//
// Supported platforms:
//   - YouTube (via ytInitialPlayerResponse embedded in page source)
//   - Microsoft Stream / SharePoint video (via <track> elements or transcript panel)

(async function() {
	// --- Platform detection ---

	interface TranscriptResult {
		action: "transcriptCaptureComplete";
		success: boolean;
		platform: string | null;
		transcript: TranscriptEntry[] | string | null;
		videoTitle: string | null;
		language: string | null;
		availableLanguages: LanguageOption[] | null;
		error: string | null;
		// For deferred fetch: if the content script can't fetch directly,
		// provide the URL for the service worker to fetch.
		captionUrl: string | null;
	}

	interface TranscriptEntry {
		startMs: number;
		durationMs: number;
		text: string;
	}

	interface LanguageOption {
		code: string;
		name: string;
		baseUrl: string;
		isAutoGenerated: boolean;
	}

	function detectPlatform(): string | null {
		let host = window.location.hostname.toLowerCase();
		if (host === "www.youtube.com" || host === "youtube.com" || host === "youtu.be" || host === "m.youtube.com") {
			return "youtube";
		}
		if (host.indexOf(".sharepoint.com") !== -1 || host.indexOf("stream.microsoft.com") !== -1) {
			return "microsoftstream";
		}
		return null;
	}

	// --- YouTube extraction (DOM-based) ---

	async function extractYouTubeTranscriptInfo(): Promise<TranscriptResult> {
		let videoTitle = document.title || null;

		// Step 1: Expand the description if collapsed
		let expandBtn = document.querySelector(
			"tp-yt-paper-button#expand.ytd-text-inline-expander"
		) as HTMLElement | null;
		if (expandBtn) {
			expandBtn.click();
			await new Promise(function(r) { setTimeout(r, 500); });
		}

		// Step 2: Click "Show transcript" button
		let transcriptBtn = document.querySelector(
			"ytd-video-description-transcript-section-renderer button[aria-label=\"Show transcript\"]"
		) as HTMLElement | null;
		if (!transcriptBtn) {
			return makeError("youtube", "Could not find 'Show transcript' button. The video may not have a transcript available.");
		}
		transcriptBtn.click();

		// Step 3: Wait for the transcript panel to render
		let maxWait = 5000;
		let pollInterval = 250;
		let elapsed = 0;
		let transcriptPanel: Element | null = null;
		while (elapsed < maxWait) {
			await new Promise(function(r) { setTimeout(r, pollInterval); });
			elapsed += pollInterval;
			transcriptPanel = document.querySelector("ytd-transcript-renderer, ytd-engagement-panel-section-list-renderer[target-id=\"engagement-panel-searchable-transcript\"]");
			if (transcriptPanel) {
				await new Promise(function(r) { setTimeout(r, 500); });
				break;
			}
		}
		if (!transcriptPanel) {
			return makeError("youtube", "Transcript panel did not appear within timeout.");
		}

		// Step 4: Scrape transcript segments from the DOM
		let segments = transcriptPanel.querySelectorAll("ytd-transcript-segment-renderer");
		if (!segments || segments.length === 0) {
			segments = transcriptPanel.querySelectorAll("[class*=\"segment\"]");
		}
		if (!segments || segments.length === 0) {
			return makeError("youtube", "Transcript panel opened but no segments found.");
		}

		let entries: TranscriptEntry[] = [];
		for (let i = 0; i < segments.length; i++) {
			let seg = segments[i] as HTMLElement;
			let timestampEl = seg.querySelector(".segment-timestamp, [class*=\"timestamp\"]") as HTMLElement | null;
			let textEl = seg.querySelector(".segment-text, yt-formatted-string, [class*=\"text\"]") as HTMLElement | null;
			let timestamp = timestampEl?.innerText?.trim() || "";
			let text = textEl?.innerText?.trim() || seg.innerText?.trim() || "";
			if (text) {
				// Parse timestamp string (e.g. "1:23") into milliseconds
				let startMs = 0;
				let timeParts = timestamp.split(":").map(function(p) { return parseInt(p, 10) || 0; });
				if (timeParts.length === 3) {
					startMs = (timeParts[0] * 3600 + timeParts[1] * 60 + timeParts[2]) * 1000;
				} else if (timeParts.length === 2) {
					startMs = (timeParts[0] * 60 + timeParts[1]) * 1000;
				}
				entries.push({ startMs: startMs, durationMs: 0, text: text });
			}
		}

		if (entries.length === 0) {
			return makeError("youtube", "Transcript panel rendered but could not extract text from segments.");
		}

		return {
			action: "transcriptCaptureComplete",
			success: true,
			platform: "youtube",
			transcript: entries,
			videoTitle: videoTitle,
			language: null,
			availableLanguages: null,
			error: null,
			captionUrl: null
		};
	}

	// --- Microsoft Stream / SharePoint extraction ---

	function extractStreamTranscript(): TranscriptResult {
		let videoTitle = document.title || null;

		// Strategy 1: Look for <track> elements on <video> tags
		let video = document.querySelector("video");
		if (video) {
			let tracks = video.querySelectorAll("track");
			if (tracks.length > 0) {
				// Find a captions or subtitles track
				let captionTrack: HTMLTrackElement | null = null;
				for (let i = 0; i < tracks.length; i++) {
					let t = tracks[i] as HTMLTrackElement;
					if (t.kind === "captions" || t.kind === "subtitles") {
						captionTrack = t;
						break;
					}
				}
				if (!captionTrack && tracks.length > 0) {
					captionTrack = tracks[0] as HTMLTrackElement;
				}
				if (captionTrack?.src) {
					return {
						action: "transcriptCaptureComplete",
						success: true,
						platform: "microsoftstream",
						transcript: null,
						videoTitle: videoTitle,
						language: captionTrack.srclang || null,
						availableLanguages: null,
						error: null,
						captionUrl: captionTrack.src
					};
				}
			}
		}

		// Strategy 2: Look for rendered transcript panel in DOM
		let transcriptSection = document.querySelector(
			'section[aria-label="Transcript"], [data-automation-id="transcript-panel"], .transcript-container'
		);
		if (transcriptSection) {
			let lines = transcriptSection.querySelectorAll('[role="listitem"], .transcript-line, [data-automation-id="transcript-segment"]');
			if (lines.length > 0) {
				let entries: TranscriptEntry[] = [];
				for (let i = 0; i < lines.length; i++) {
					let line = lines[i] as HTMLElement;
					let text = line.innerText?.trim();
					if (text) {
						entries.push({
							startMs: i * 1000, // Approximation — real timestamps not always exposed in DOM
							durationMs: 1000,
							text: text
						});
					}
				}
				return {
					action: "transcriptCaptureComplete",
					success: true,
					platform: "microsoftstream",
					transcript: entries,
					videoTitle: videoTitle,
					language: null,
					availableLanguages: null,
					error: null,
					captionUrl: null
				};
			}
		}

		// Strategy 3: Check for VTT URLs in page source (some Stream embeds have them in scripts/data attributes)
		let allElements = document.querySelectorAll("[data-vtt-url], [data-captions-url]");
		for (let i = 0; i < allElements.length; i++) {
			let el = allElements[i] as HTMLElement;
			let vttUrl = el.getAttribute("data-vtt-url") || el.getAttribute("data-captions-url");
			if (vttUrl) {
				return {
					action: "transcriptCaptureComplete",
					success: true,
					platform: "microsoftstream",
					transcript: null,
					videoTitle: videoTitle,
					language: null,
					availableLanguages: null,
					error: null,
					captionUrl: vttUrl
				};
			}
		}

		return makeError("microsoftstream", "Could not find transcript data. Ensure the video has captions enabled.");
	}

	// --- Helpers ---

	function makeError(platform: string, message: string): TranscriptResult {
		return {
			action: "transcriptCaptureComplete",
			success: false,
			platform: platform,
			transcript: null,
			videoTitle: null,
			language: null,
			availableLanguages: null,
			error: message,
			captionUrl: null
		};
	}

	// --- Main ---

	let platform = detectPlatform();
	let result: TranscriptResult;

	if (platform === "youtube") {
		result = await extractYouTubeTranscriptInfo();
	} else if (platform === "microsoftstream") {
		result = extractStreamTranscript();
	} else {
		result = makeError(null, "This page is not a supported video platform (YouTube or Microsoft Stream).");
	}

	chrome.runtime.sendMessage(JSON.stringify(result));
})();
