export const ClipperStorageKeys = {
	clipperId: "clipperId",
	cachedNotebooks: "notebooks",
	currentSelectedSection: "curSection",
	displayLanguageOverride: "displayLocaleOverride",
	doNotPromptRatings: "doNotPromptRatings",
	flightingInfo: "flightingInfo",
	hasPatchPermissions: "hasPatchPermissions",
	lastBadRatingDate: "lastBadRatingDate",
	lastBadRatingVersion: "lastBadRatingVersion",
	lastClippedDate: "lastClippedDate",
	lastSeenVersion: "lastSeenVersion",
	lastInvokedDate: "lastInvokedDate",
	lastSeenTooltipTimeBase: "lastSeenTooltipTime",
	lastClippedTooltipTimeBase: "lastClippedTooltipTime",
	locale: "locale",
	locStrings: "locStrings",
	numSuccessfulClips: "numSuccessfulClips",
	numSuccessfulClipsRatingsEnablement: "numSuccessfulClipsRatingsEnablement",
	numTimesTooltipHasBeenSeenBase: "numTimesTooltipHasBeenSeen",
	userInformation: "userInformation"
};
